[build]
  command = "flutter build web --release --dart-define=SAFEBITE_API_URL=https://safe-bite-bocd.onrender.com/api"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.24.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
